export const UPDATE_HIGHEST_SCORE = "UPDATE_HIGHEST_SCORE";
export const RESET_HIGHEST_SCORE = "RESET_HIGHEST_SCORE";

export const UPDATE_ACTIVE_SCORE = "UPDATE_HIGHEST_SCORE";
export const RESET_ACTIVE_SCORE = "RESET_HIGHEST_SCORE";
